services:
  db:
    image: postgres:16-alpine
    restart: 'no'
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  scraper:
    image: collect-prices-in-web-scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    restart: 'no'
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./scraper:/app
      - ./shared:/app/shared
    command: python main.py
    profiles:
      - manual

  scraper-worker:
    container_name: scraper-worker
    image: collect-prices-in-web-scraper
    build:
      context: .
      dockerfile: scraper/Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./scraper:/app
      - ./shared:/app/shared
    command: python worker.py

  scheduler:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    depends_on:
      - db
      - scraper-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia.ini:/etc/ofelia/config.ini

  api:
    build:
      context: .
      dockerfile: backend/api/Dockerfile
    restart: 'no'
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./shared:/app/shared

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - "5173:5173"
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
